### ISSUE TITLE
How to use the SCAN image feature in GSMN?

### ISSUE THREAD

**Issue by harukaza** [CrossmodalGroup/GSMN#3]
Thanks for your share ! I am training the SCAN model now, but I don't know what features can be use in the GSMN. 
------
now I confuse how  to set the parameters in SCAN training. Can you provide more details about the model?

**Comment by YuehuaZhu** [comment]
同问，如何使用updown特征

**Comment by CrossmodalGroup** [comment]
Thanks for your attention. You should create two new folders, named as f30k_precomp and coco_precomp. Then, you need to download image feature from SCAN https://github.com/kuanghuei/SCAN, and other features provided by us from https://drive.google.com/file/d/1ZVLIN7uSh3dqYAEldelyYF2ei9vicJvZ/view?usp=sharing, and put corresponding features at newly created folders. When training the model, you should specify the data directory using "--data_path” in the Python script.

**Comment by YuehuaZhu** [comment]
> Thanks for your attention. You should create two new folders, named as f30k_precomp and coco_precomp. Then, you need to download image feature from SCAN https://github.com/kuanghuei/SCAN, and other features provided by us from https://drive.google.com/file/d/1ZVLIN7uSh3dqYAEldelyYF2ei9vicJvZ/view?usp=sharing, and put corresponding features at newly created folders. When training the model, you should specify the data directory using "--data_path” in the Python script.

Thank you!

**Comment by harukaza** [comment]
Thank you for your answer!

**Comment by 184446223** [comment]
> 感谢您的关注。您应该创建两个新文件夹，命名为 f30k_precomp 和 coco_precomp。然后，您需要从 SCAN [https://github.com/kuanghuei/SCAN下载图像功能，以及从](https://github.com/kuanghuei/SCAN)https://drive.google.com/file/d/1ZVLIN7uSh3dqYAEldelyYF2ei9vicJvZ/view?usp=sharing下载我们提供的其他功能, 并将相应的功能放在新创建的文件夹中。训练模型时，应在 Python 脚本中使用“--data_path”指定数据目录。

How to get the image region boxes of the image feature,and the bbox and the image feature is matching?
