### ISSUE TITLE
Implementation for sparse+dense

### ISSUE THREAD

**Issue by detectiveli** [CrossmodalGroup/GSMN#6]
Dear contribution,

I read your paper and the best performance is sparse+dense. May I ask how to use sparse+dense but you only provide the config file with sparse or dense.

Thank you very much.

**Comment by CrossmodalGroup** [comment]
We have uploaded the Python script ''test_stack.py'' to ensemble sparse and dense model, thanks!

**Comment by detectiveli** [comment]
Everything works fine, and many thanks for your kindly reply.
